<?php
namespace Database\Seeders;

use App\Models\Lga;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class LgasTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('lgas')->delete();

        $state_id =[
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            106,
            107,
            108,
            109,
            110,
            111,
            112,
            113,
            114,
            115,
            116,
            117,
        ];

        $lgas = ["Dhanmondi", "Panthpath", "Kalabagan", "Arong", "Noakhali", "Banani", "Uttara", "Abdullahpur", "Mohammadpur", "Chatkhil", "Chadpur", "Sukrabad", "Malibagh", "Gulsan", "Mohakhali", "Badda", "Diyabari", "Airport", "Basundhara Resiential", "Mirpur", "Mirpur-1", "Mirpur-2", "Mirpur-10", "Mirpur-11", "Mirpur-12", "Mirpur-13", "Mirpur-14", "Mirpur-6", "Pallobi", "Baridhara", "Jatrabari", "Narayganj", "Gulistan", "Shabagh", "Paltan", "Turag", "Tongi", "Khilgaon", "Rampura", "Mochak", "Framgate", "Bangla Motor", "Kakrail", "Tejgaon", "Dhamondi-27", "Dhamondi-32", "Dhamondi-9", "Dhamondi-10", "Dhamondi-15", "Jigatola", "New Market", "Nilkhet", "Azimpur", "Lalbagh", "Sadarghat", "Ahsan Monjil", "Babu Bazar", "Khilkhet", "Nikunja", "Kuril", "Josim Uddin", "Kakoli", "Amtoli", "Noddda", "Progoti Saroni", "Shazadpur", "Bosila", "Kafrul", "Sonaimuni", "Majgdhi", "Company Bazar", "Feni", "Sonagasa", "Begumganj", "Chowhomuni", "Ramganj", "Joyag", "Townhall", "Asad Gate", "Symoli", "Kallanpur", "Technical", "Gabtoli", "Rayer Bazar", "SignBoard", "puran Dhaka", "Belly Road", "Love Road", "Bangshal", "SheikherTag", "Adabor", "Arambagh", "Golapbag", "TT Para", "KamalaPur", "Pressclub", "Shantinagar", "Kodomtoli", "Janata", "Fokirapull", "Motijhill", "Hatirpull", "Elepent Road", "Bata Signal", "Science Lab", "City college", "pillkhana", "Mohakhali DOHS", "Mirpur DOHS", "Matikata", "Sagupta", "emg", "Ibrahimpur", "Agargon", "Taltola", "Sherapara", "Kazipara",
        ];

        for($i=0; $i<count($lgas); $i++){
            Lga::create(['state_id' => $state_id[$i], 'name' => $lgas[$i]]);
        }
    }

}
